### ISSUE TITLE
[feature request] use windows-service crate rather than sc.exe

### ISSUE THREAD

**Issue by xuyang2** [chipsenkbeil/service-manager-rs#2]
- https://crates.io/crates/windows-service
- https://github.com/mullvad/windows-service-rs

**Comment by chipsenkbeil** [comment]
I'm aware of the crate as I use it for the actual service implementation in my system tests [as seen here](https://github.com/chipsenkbeil/service-manager-rs/blob/main/system-tests/src/main.rs#L201).

Is there a reason you would prefer the implementation to use that crate over talking to `sc.exe`? My reason for not using it for the installation was to avoid another unnecessary dependency.

**Comment by chipsenkbeil** [comment]
Closing out due to lack of input.

**Comment by nu11ptr** [comment]
One reason to prefer it would be to have a less brittle interface to the system. If sc.exe changes parameter names in an upcoming version of Windows, this crate would break where as using something that uses the underlying win32 API would not.

**Comment by chipsenkbeil** [comment]
> One reason to prefer it would be to have a less brittle interface to the system. If `sc.exe` changes parameter names in an upcoming version of Windows, this crate would break where as using something that uses the underlying win32 API would not.
> 
> In my `rust_format` crate I did the same when calling out to `rustfmt`, however, in that case it was a HUGE dependency and it relied on nightly if I recall. In this case, I would think calling the API would be a good trade off for another dependency to prevent brittleness, a moved or deleted `sc.exe` file, etc.. My 2 cents only.

@nu11ptr Do you expect a core service binary like `sc.exe` to change its arguments that often? And if it did, would we expect the win32 API to be much more resilient? Honest question here since I don't use Windows! 😄 

I have some experience using the crate referenced since I've written two windows services using it, and this could potentially be a feature flag to unlock an additional option that uses windows-service instead of `sc.exe`, but I'd say it's of a lower priority than adding other platforms like runit.

I'm also not opposed to a PR that adds this!

Thoughts?

**Comment by nu11ptr** [comment]
> Do you expect a core service binary like sc.exe to change its arguments that often?

No, but I don't think Microsoft would hestitate to change it either if they had a need to do it. It isn't designed to be used by a human.

> And if it did, would we expect the win32 API to be much more resilient?

Yes, win32 doesn't break backwards compatibility. I'm not a huge windows fan, but Win32 has been around forever... and changes are backwards compatible always AFAIK (which is why they keep adding `Ex` suffix functions when a similar function needs new params)

The culture on unix is that generally core programs are stable parameter-wise because they are called from scripts. Windows does not have this culture. The closest they now have is Powershell, but that uses objects/apis as well, not programs AFAIK.

I also am not an expert here, but drawing from past knowledge. I also don't have a huge need or opinion just more surprised since I've never seen Windows Services implemented programatically this way (every lang bindings I've seen uses the API, doesn't make it better, just what I've seen).
