### ISSUE TITLE
Question: how to ask admin in rust?

### ISSUE THREAD

**Issue by loafman-kangjun** [chipsenkbeil/service-manager-rs#28]
It needs admin when installing and setting service
I want to ask that if Ican have any ways to get admin by using Rust (such as Sudo UAC) during application execution

**Comment by 0xffffharry** [comment]
> It needs admin when installing and setting service  I want to ask that if Ican have any ways to get admin by using Rust (such as Sudo UAC) during application execution

You can use "runas" crate.

**Comment by chipsenkbeil** [comment]
@0xffffharry's recommendation is what I'd do. Getting admin access is a separate issue that I'd say is out of scope for this crate in terms of implementing from scratch. I wouldn't be opposed to supporting integrating something like [`runas`](https://crates.io/crates/runas) as a feature in the future, though.

If either of you is interested in doing that, let me know. For now, going to close this out since we have a path forward.
